import { signIn,signUp,signOut,getSession,onAuthChange } from './auth.js';
import { ensureProfile,foundationHealthCheck } from './database.js';
import { listFamilyData,sendFamilyInvite,respondFamilyInvite,cancelFamilyInvite,updateFamilyPermissions,removeFamilyLink,loadFamilyOverview } from './family.js';
import { getLegacyMigrationStatus,claimLegacyAccount } from './migration.js';
import { updateProfileSettings } from './settings.js';
import { initPWA } from './pwa.js';
import { DEFAULT_CATEGORIES,localISO,monthInputValue,listTransactions,createTransaction,updateTransaction,deleteTransaction,applyBalanceAdjustment,calculateCashStats,filterTransactions } from './finance.js';
import { listCards,createCard,updateCard,deleteCard,createPurchase,updatePurchase,deletePurchase,listPurchases,listInstallments,listInvoiceStatuses,setInvoicePaid,sumCardExpensesForMonth,cardInvoiceSummaries } from './cards.js';
import { listGoals,createGoal,updateGoal,deleteGoal } from './goals.js';
import { BUDGET_CATEGORIES,getBudget,saveBudget,budgetSummary } from './budget.js';
import { setAuthMode,showAuth,showApp,showModule,setAuthError,setAuthBusy,toast,setLoading,formatBRL,formatDate,monthLabel,escapeHTML,openDialog,closeDialog,setFormError,emptyState,applyTheme } from './ui.js';

let authMode='login', booting=false, refreshBusy=false;
let currentUser=null, currentProfile=null;
let dashboardDate=new Date(new Date().getFullYear(),new Date().getMonth(),1,12);
let budgetDate=new Date(new Date().getFullYear(),new Date().getMonth(),1,12);
let state={transactions:[],cards:[],purchases:[],installments:[],invoiceStatuses:[],goals:[],budget:{plan:null,items:[]},family:null,migration:{claimed:false}};

function fillCategorySelect(id){const el=document.getElementById(id);el.innerHTML=DEFAULT_CATEGORIES.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join('')}
function monthPrefix(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function addMonth(date,offset){return new Date(date.getFullYear(),date.getMonth()+offset,1,12)}
function setButtonBusy(btn,busy,text='Salvando…'){if(!btn)return;if(busy){btn.dataset.oldText=btn.textContent;btn.textContent=text;btn.disabled=true}else{btn.textContent=btn.dataset.oldText||btn.textContent;btn.disabled=false}}

async function enterApp(session){if(!session?.user||booting)return;booting=true;try{currentUser=session.user;currentProfile=await ensureProfile(session.user);await foundationHealthCheck(session.user.id);showApp(session.user,currentProfile);showModule('home');await refreshAll()}catch(error){console.error(error);showAuth();toast('A nova base não conseguiu carregar seus dados.','error')}finally{booting=false}}

async function refreshAll(){if(refreshBusy)return;refreshBusy=true;setLoading(true);try{const [transactions,cards,purchases,installments,invoiceStatuses,goals,budget,family,migration]=await Promise.all([listTransactions(),listCards(),listPurchases(),listInstallments(),listInvoiceStatuses(),listGoals(),getBudget(budgetDate),listFamilyData(),getLegacyMigrationStatus()]);state={transactions,cards,purchases,installments,invoiceStatuses,goals,budget,family,migration};renderAll()}catch(error){console.error(error);toast(error?.message||'Falha ao sincronizar dados.','error')}finally{setLoading(false);refreshBusy=false}}

function renderAll(){renderHome();renderTransactions();renderCards();renderGoals();renderBudget();renderFamily();renderSettings()}

function renderHome(){
  document.getElementById('home-month-label').textContent=monthLabel(dashboardDate);document.getElementById('home-period').textContent=`Referência: ${monthLabel(dashboardDate)}`;
  const cash=calculateCashStats(state.transactions,dashboardDate);const cardExpense=sumCardExpensesForMonth(state.installments,dashboardDate);const result=cash.cashResult-cardExpense;const invoiceSummaries=cardInvoiceSummaries(state.cards,state.installments,state.invoiceStatuses,dashboardDate);const openCardTotal=invoiceSummaries.filter(s=>s.status!=='paid').reduce((sum,s)=>sum+s.total,0);const projected=cash.projectedCashBalance-openCardTotal;
  document.getElementById('stat-balance').textContent=formatBRL(cash.balance);document.getElementById('stat-income').textContent=formatBRL(cash.income);document.getElementById('stat-expense').textContent=formatBRL(cash.expense+cardExpense);document.getElementById('stat-card-expense').textContent=formatBRL(cardExpense);document.getElementById('stat-month-result').textContent=formatBRL(result);document.getElementById('stat-projected').textContent=formatBRL(projected);
  const recent=state.transactions.slice(0,5);document.getElementById('home-transactions').innerHTML=recent.length?recent.map(transactionRowHTML).join(''):emptyState('Nenhum lançamento nesta conta de testes.');
  const summaries=invoiceSummaries.filter(s=>s.total>0).sort((a,b)=>a.dueDate-b.dueDate).slice(0,4);document.getElementById('home-invoices').innerHTML=summaries.length?summaries.map(s=>`<div class="list-row"><div class="list-row-main"><div class="list-row-title">${escapeHTML(s.card.name)}</div><div class="list-row-meta"><span>Vence ${s.dueDate.toLocaleDateString('pt-BR')}</span><span>${s.status==='paid'?'Paga':'Aberta'}</span></div></div><div class="list-row-amount">${formatBRL(s.total)}</div></div>`).join(''):emptyState('Nenhuma fatura com valor neste mês.');
  const goals=state.goals.filter(g=>g.status!=='archived').slice(0,4);document.getElementById('home-goals').innerHTML=goals.length?goals.map(goalMiniHTML).join(''):emptyState('Nenhuma meta cadastrada.');
  const bs=budgetSummary(state.budget,state.transactions,state.installments,budgetDate);document.getElementById('home-budget-spent').textContent=formatBRL(bs.totalSpent);document.getElementById('home-budget-limit').textContent=`de ${formatBRL(bs.totalLimit)}`;document.getElementById('home-budget-caption').textContent=bs.totalLimit?`${Math.max(0,Math.min(100,(bs.totalSpent/bs.totalLimit)*100)).toFixed(0)}% utilizado`:'Nenhum orçamento definido.';document.getElementById('home-budget-progress').style.width=bs.totalLimit?`${Math.max(0,Math.min(100,(bs.totalSpent/bs.totalLimit)*100))}%`:'0%';
}

function transactionRowHTML(t){const signed=Number(t.direction)*Number(t.amount||0);const isAdj=t.type==='balance_adjustment';return `<div class="list-row"><div class="list-row-main"><div class="list-row-title">${escapeHTML(t.description)}</div><div class="list-row-meta"><span>${escapeHTML(t.category||'Outros')}</span><span>${formatDate(t.occurred_on)}</span>${t.recurring_group_id?'<span>Recorrente</span>':''}${isAdj?'<span>Ajuste</span>':''}</div></div><div><div class="list-row-amount ${signed>=0?'positive':'negative'}">${signed>=0?'+':'-'} ${formatBRL(Math.abs(signed))}</div><div class="row-actions">${isAdj?'':`<button class="mini-btn" data-edit-transaction="${t.id}">Editar</button>`}<button class="mini-btn danger" data-delete-transaction="${t.id}">Excluir</button></div></div></div>`}
function renderTransactions(){const search=document.getElementById('transaction-search').value||'';const type=document.getElementById('transaction-filter-type').value||'all';const month=document.getElementById('transaction-filter-month').value||'';const rows=filterTransactions(state.transactions,{search,type,month});document.getElementById('transactions-list').innerHTML=rows.length?rows.map(transactionRowHTML).join(''):emptyState('Nenhum lançamento encontrado.')}

function renderCards(){
  document.getElementById('cards-list').innerHTML=state.cards.length?state.cards.map(card=>{const all=state.installments.filter(i=>i.card_id===card.id);const paidMonths=new Set(state.invoiceStatuses.filter(x=>x.card_id===card.id&&x.status==='paid').map(x=>x.invoice_month));const outstanding=all.filter(i=>!paidMonths.has(i.invoice_month)).reduce((a,b)=>a+Number(b.amount||0),0);const available=Number(card.credit_limit)-outstanding;return `<article class="credit-card"><div class="credit-card-head"><div><span class="eyebrow">CARTÃO</span><h3>${escapeHTML(card.name)}</h3></div><span>${card.closing_day}/${card.due_day}</span></div><div class="credit-limit">${formatBRL(card.credit_limit)}</div><div class="credit-meta"><span>Comprometido ${formatBRL(outstanding)}</span><span>Disponível ${formatBRL(available)}</span><span>Juros ${Number(card.revolving_interest||0).toFixed(2)}%</span></div><div class="card-actions"><button class="mini-btn" data-new-purchase="${card.id}">＋ Compra</button><button class="mini-btn" data-open-invoice="${card.id}">Fatura</button><button class="mini-btn" data-edit-card="${card.id}">Editar</button><button class="mini-btn danger" data-delete-card="${card.id}">Excluir</button></div></article>`}).join(''):emptyState('Nenhum cartão cadastrado.');
  document.getElementById('card-purchases-list').innerHTML=state.purchases.length?state.purchases.map(p=>`<div class="list-row"><div class="list-row-main"><div class="list-row-title">${escapeHTML(p.description)}</div><div class="list-row-meta"><span>${escapeHTML(p.ff2_cards?.name||'Cartão')}</span><span>${formatDate(p.purchase_date)}</span><span>${p.installment_count}x</span><span>${escapeHTML(p.category||'Outros')}</span></div></div><div><div class="list-row-amount">${formatBRL(p.total_amount)}</div><div class="row-actions"><button class="mini-btn" data-edit-purchase="${p.id}">Editar</button><button class="mini-btn danger" data-delete-purchase="${p.id}">Excluir</button></div></div></div>`).join(''):emptyState('Nenhuma compra cadastrada.');
}

function goalMiniHTML(g){const pct=Math.max(0,Math.min(100,(Number(g.saved_amount)/Number(g.target_amount||1))*100));return `<div class="list-row"><div class="list-row-main"><div class="list-row-title">${escapeHTML(g.name)}</div><div class="progress"><span style="width:${pct}%"></span></div><div class="list-row-meta"><span>${pct.toFixed(0)}%</span><span>${formatBRL(g.saved_amount)} de ${formatBRL(g.target_amount)}</span></div></div></div>`}
function renderGoals(){document.getElementById('goals-list').innerHTML=state.goals.length?state.goals.map(g=>{const pct=Math.max(0,Math.min(100,(Number(g.saved_amount)/Number(g.target_amount||1))*100));return `<article class="goal-card"><div class="goal-card-head"><div><span class="eyebrow">${g.status==='completed'?'CONCLUÍDA':'META'}</span><h3>${escapeHTML(g.name)}</h3></div>${g.due_date?`<span>${formatDate(g.due_date)}</span>`:''}</div><div class="goal-amounts"><strong>${formatBRL(g.saved_amount)}</strong><span>de ${formatBRL(g.target_amount)}</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="progress-meta"><span>${pct.toFixed(0)}%</span><span>Faltam ${formatBRL(Math.max(0,Number(g.target_amount)-Number(g.saved_amount)))}</span></div><div class="card-actions"><button class="mini-btn" data-edit-goal="${g.id}">Editar</button><button class="mini-btn danger" data-delete-goal="${g.id}">Excluir</button></div></article>`}).join(''):emptyState('Nenhuma meta cadastrada.')}

function renderBudget(){document.getElementById('budget-month-label').textContent=monthLabel(budgetDate);document.getElementById('budget-income').value=Number(state.budget.plan?.planned_income||0)||'';const bs=budgetSummary(state.budget,state.transactions,state.installments,budgetDate);document.getElementById('budget-items').innerHTML=BUDGET_CATEGORIES.map(cat=>`<div class="budget-item"><div><span>${escapeHTML(cat)}</span><small>Gasto: ${formatBRL(bs.spentMap[cat]||0)}</small></div><input type="number" min="0" step="0.01" data-budget-category="${escapeHTML(cat)}" value="${bs.itemMap[cat]||''}" placeholder="0,00"></div>`).join('');document.getElementById('budget-total-limit').textContent=formatBRL(bs.totalLimit);document.getElementById('budget-total-spent').textContent=formatBRL(bs.totalSpent);document.getElementById('budget-total-available').textContent=formatBRL(bs.available)}

function familyProfileName(id){const p=state.family?.profiles?.find(x=>x.user_id===id);return p?.display_name||'Membro da família'}
function permissionTags(link){const items=[['transactions','Lançamentos',link.can_view_transactions],['cards','Cartões',link.can_view_cards],['goals','Metas',link.can_view_goals],['budget','Orçamento',link.can_view_budget]];return `<div class="permission-tags">${items.map(([,label,on])=>`<span class="permission-tag ${on?'on':''}">${label}</span>`).join('')}</div>`}
function familyPersonHTML({name,subtitle='',actions='',tags=''}){const initial=escapeHTML(String(name||'F').trim().charAt(0).toUpperCase()||'F');return `<div class="family-person"><div class="family-avatar">${initial}</div><div class="family-person-main"><strong>${escapeHTML(name||'Família')}</strong><small>${escapeHTML(subtitle)}</small>${tags}</div><div class="family-actions">${actions}</div></div>`}
function renderFamily(){const data=state.family;if(!data)return;const me=data.user.id;const incoming=data.invites.filter(i=>i.status==='pending'&&i.inviter_user_id!==me);const outgoing=data.invites.filter(i=>i.status==='pending'&&i.inviter_user_id===me);const viewing=data.links.filter(l=>l.active&&l.viewer_user_id===me);const viewers=data.links.filter(l=>l.active&&l.owner_user_id===me);
  document.getElementById('family-incoming').innerHTML=incoming.length?incoming.map(i=>familyPersonHTML({name:familyProfileName(i.inviter_user_id),subtitle:'Quer compartilhar o financeiro com você',actions:`<button class="mini-btn" data-family-respond="${i.id}" data-accept="1">Aceitar</button><button class="mini-btn danger" data-family-respond="${i.id}" data-accept="0">Recusar</button>`})).join(''):emptyState('Nenhum convite pendente.');
  document.getElementById('family-viewing').innerHTML=viewing.length?viewing.map(l=>familyPersonHTML({name:familyProfileName(l.owner_user_id),subtitle:'Você possui acesso autorizado',tags:permissionTags(l),actions:`<button class="mini-btn" data-family-monitor="${l.owner_user_id}">Visualizar</button><button class="mini-btn danger" data-family-remove="${l.id}">Sair</button>`})).join(''):emptyState('Você ainda não acompanha ninguém.');
  document.getElementById('family-viewers').innerHTML=viewers.length?viewers.map(l=>familyPersonHTML({name:familyProfileName(l.viewer_user_id),subtitle:'Pode acompanhar os grupos autorizados',tags:permissionTags(l),actions:`<button class="mini-btn" data-family-permissions="${l.id}">Permissões</button><button class="mini-btn danger" data-family-remove="${l.id}">Remover</button>`})).join(''):emptyState('Ninguém acompanha seus dados atualmente.');
  document.getElementById('family-outgoing').innerHTML=outgoing.length?outgoing.map(i=>familyPersonHTML({name:i.invitee_email,subtitle:'Convite enviado — aguardando resposta',actions:`<button class="mini-btn danger" data-family-cancel-invite="${i.id}">Cancelar</button>`})).join(''):emptyState('Nenhum convite enviado aguardando resposta.');
}
function renderSettings(){if(!currentProfile)return;const nameInput=document.getElementById('settings-display-name');if(nameInput&&document.activeElement!==nameInput)nameInput.value=currentProfile.display_name||'';applyTheme(currentProfile.theme||'system');const status=state.migration||{claimed:false};const pill=document.getElementById('migration-status-pill'),form=document.getElementById('legacy-migration-form'),done=document.getElementById('migration-complete');if(status.claimed){pill.textContent='Migrado';pill.classList.add('ok');form.classList.add('hidden');done.classList.remove('hidden');done.textContent=`Dados antigos vinculados ao usuário “${status.legacy_username}”. O backup legado permanece preservado.`}else{pill.textContent='Não migrado';pill.classList.remove('ok');form.classList.remove('hidden');done.classList.add('hidden')}}

async function openFamilyMonitor(ownerId){const link=state.family?.links?.find(l=>l.owner_user_id===ownerId&&l.viewer_user_id===currentUser?.id&&l.active);if(!link)return;setLoading(true);try{const data=await loadFamilyOverview(ownerId,dashboardDate);const name=familyProfileName(ownerId);document.getElementById('family-monitor-name').textContent=name;const tx=data.transactions||[];const month=monthPrefix(dashboardDate);const today=localISO();let balance=0,income=0,expense=0;tx.forEach(t=>{const signed=Number(t.direction)*Number(t.amount||0);if(t.occurred_on<=today)balance+=signed;if(String(t.occurred_on).startsWith(month)&&t.affects_month_result){if(signed>=0)income+=signed;else expense+=Math.abs(signed)}});const cardMonth=(data.installments||[]).reduce((a,b)=>a+Number(b.amount||0),0);const budgetLimit=(data.budget?.items||[]).reduce((a,b)=>a+Number(b.limit_amount||0),0);const metrics=[];if(link.can_view_transactions)metrics.push(['Saldo',formatBRL(balance)],['Receitas',formatBRL(income)],['Despesas',formatBRL(expense)]);if(link.can_view_cards)metrics.push(['Cartão no mês',formatBRL(cardMonth)]);if(link.can_view_goals)metrics.push(['Metas ativas',String((data.goals||[]).filter(g=>g.status!=='completed').length)]);if(link.can_view_budget)metrics.push(['Orçamento',formatBRL(budgetLimit)]);document.getElementById('family-monitor-metrics').innerHTML=metrics.length?metrics.map(([label,value])=>`<article class="metric-card"><span>${escapeHTML(label)}</span><strong>${escapeHTML(value)}</strong></article>`).join(''):emptyState('Nenhum grupo foi compartilhado.');document.getElementById('family-monitor-transactions').innerHTML=link.can_view_transactions&&tx.length?tx.slice(0,6).map(t=>`<div class="list-row"><div class="list-row-main"><div class="list-row-title">${escapeHTML(t.description)}</div><div class="list-row-meta"><span>${formatDate(t.occurred_on)}</span><span>${escapeHTML(t.category||'Outros')}</span></div></div><div class="list-row-amount ${Number(t.direction)>0?'positive':'negative'}">${formatBRL(Number(t.amount||0))}</div></div>`).join(''):emptyState(link.can_view_transactions?'Nenhum lançamento.':'Lançamentos não compartilhados.');document.getElementById('family-monitor-goals').innerHTML=link.can_view_goals&&data.goals?.length?data.goals.slice(0,5).map(goalMiniHTML).join(''):emptyState(link.can_view_goals?'Nenhuma meta.':'Metas não compartilhadas.');document.getElementById('family-monitor-panel').classList.remove('hidden');document.getElementById('family-monitor-panel').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error(e);toast('Não foi possível abrir os dados familiares.','error')}finally{setLoading(false)}}
function openFamilyPermissions(linkId){const link=state.family?.links?.find(l=>l.id===linkId&&l.owner_user_id===currentUser?.id);if(!link)return;document.getElementById('family-link-id').value=link.id;document.getElementById('family-permissions-title').textContent=familyProfileName(link.viewer_user_id);document.getElementById('perm-transactions').checked=!!link.can_view_transactions;document.getElementById('perm-cards').checked=!!link.can_view_cards;document.getElementById('perm-goals').checked=!!link.can_view_goals;document.getElementById('perm-budget').checked=!!link.can_view_budget;setFormError('family-permissions-error','');openDialog('family-permissions-dialog')}


function openNewTransaction(){document.getElementById('transaction-form').reset();document.getElementById('transaction-id').value='';document.getElementById('transaction-dialog-title').textContent='Novo lançamento';document.getElementById('transaction-date').value=localISO();document.getElementById('transaction-recurring-count').value='12';document.getElementById('recurring-fields').classList.remove('hidden');document.getElementById('recurring-count-wrap').classList.add('hidden');setFormError('transaction-form-error','');openDialog('transaction-dialog')}
function openEditTransaction(id){const t=state.transactions.find(x=>x.id===id);if(!t||t.type==='balance_adjustment')return;document.getElementById('transaction-form').reset();document.getElementById('transaction-id').value=t.id;document.getElementById('transaction-dialog-title').textContent='Editar lançamento';document.getElementById('transaction-direction').value=String(t.direction);document.getElementById('transaction-description').value=t.description||'';document.getElementById('transaction-amount').value=Number(t.amount);document.getElementById('transaction-date').value=t.occurred_on;document.getElementById('transaction-category').value=t.category||'Outros';document.getElementById('transaction-notes').value=t.notes||'';document.getElementById('recurring-fields').classList.add('hidden');setFormError('transaction-form-error','');openDialog('transaction-dialog')}
function openBalance(){const cash=calculateCashStats(state.transactions,dashboardDate);document.getElementById('balance-form').reset();document.getElementById('balance-dialog-current').textContent=formatBRL(cash.balance);document.getElementById('balance-date').value=localISO();setFormError('balance-form-error','');openDialog('balance-dialog')}
function openNewCard(){document.getElementById('card-form').reset();document.getElementById('card-id').value='';document.getElementById('card-interest').value='0';document.getElementById('card-dialog-title').textContent='Novo cartão';setFormError('card-form-error','');openDialog('card-dialog')}
function openEditCard(id){const c=state.cards.find(x=>x.id===id);if(!c)return;document.getElementById('card-id').value=c.id;document.getElementById('card-name').value=c.name;document.getElementById('card-limit').value=Number(c.credit_limit);document.getElementById('card-closing').value=c.closing_day;document.getElementById('card-due').value=c.due_day;document.getElementById('card-interest').value=Number(c.revolving_interest||0);document.getElementById('card-dialog-title').textContent='Editar cartão';setFormError('card-form-error','');openDialog('card-dialog')}
function openNewPurchase(cardId){document.getElementById('purchase-form').reset();document.getElementById('purchase-id').value='';document.getElementById('purchase-card-id').value=cardId;document.getElementById('purchase-installments').value='1';document.getElementById('purchase-date').value=localISO();document.getElementById('purchase-dialog-title').textContent=`Nova compra — ${state.cards.find(c=>c.id===cardId)?.name||'Cartão'}`;setFormError('purchase-form-error','');openDialog('purchase-dialog')}
function openEditPurchase(id){const p=state.purchases.find(x=>x.id===id);if(!p)return;document.getElementById('purchase-id').value=p.id;document.getElementById('purchase-card-id').value=p.card_id;document.getElementById('purchase-description').value=p.description;document.getElementById('purchase-total').value=Number(p.total_amount);document.getElementById('purchase-installments').value=p.installment_count;document.getElementById('purchase-date').value=p.purchase_date;document.getElementById('purchase-category').value=p.category||'Outros';document.getElementById('purchase-dialog-title').textContent='Editar compra';setFormError('purchase-form-error','');openDialog('purchase-dialog')}
function openNewGoal(){document.getElementById('goal-form').reset();document.getElementById('goal-id').value='';document.getElementById('goal-saved').value='0';document.getElementById('goal-dialog-title').textContent='Nova meta';setFormError('goal-form-error','');openDialog('goal-dialog')}
function openEditGoal(id){const g=state.goals.find(x=>x.id===id);if(!g)return;document.getElementById('goal-id').value=g.id;document.getElementById('goal-name').value=g.name;document.getElementById('goal-target').value=Number(g.target_amount);document.getElementById('goal-saved').value=Number(g.saved_amount);document.getElementById('goal-due').value=g.due_date||'';document.getElementById('goal-dialog-title').textContent='Editar meta';setFormError('goal-form-error','');openDialog('goal-dialog')}

function openInvoice(cardId){const card=state.cards.find(c=>c.id===cardId);if(!card)return;const summaries=cardInvoiceSummaries(state.cards,state.installments,state.invoiceStatuses,dashboardDate);const summary=summaries.find(s=>s.card.id===cardId);document.getElementById('invoice-title').textContent=`${card.name} — ${monthLabel(dashboardDate)}`;document.getElementById('invoice-content').innerHTML=`<div class="invoice-headline"><div><span class="muted">Fatura</span><strong>${formatBRL(summary.total)}</strong><small>Vencimento ${summary.dueDate.toLocaleDateString('pt-BR')}</small></div><button class="${summary.status==='paid'?'secondary-btn':'primary-compact'}" data-toggle-invoice="${cardId}" data-invoice-paid="${summary.status==='paid'?'1':'0'}">${summary.status==='paid'?'Reabrir fatura':'Marcar como paga'}</button></div><div class="invoice-installments">${summary.rows.length?summary.rows.map(r=>`<div class="invoice-row"><div><strong>${escapeHTML(r.ff2_card_purchases?.description||'Compra')}</strong><div class="muted">Parcela ${r.installment_no}/${r.ff2_card_purchases?.installment_count||'?'}</div></div><strong>${formatBRL(r.amount)}</strong></div>`).join(''):emptyState('Nenhuma parcela nesta fatura.')}</div>`;openDialog('invoice-dialog')}

function getDRE(refDate){const cash=calculateCashStats(state.transactions,refDate);const card=sumCardExpensesForMonth(state.installments,refDate);return {income:cash.income,cashExpense:cash.expense,cardExpense:card,totalExpense:cash.expense+card,result:cash.income-(cash.expense+card)}}
function openDRE(refDate=dashboardDate){const d=getDRE(refDate);document.getElementById('dre-title').textContent=`DRE — ${monthLabel(refDate)}`;document.getElementById('dre-content').innerHTML=`<div class="dre-grid"><div class="dre-line"><span>Receitas</span><strong class="positive">${formatBRL(d.income)}</strong></div><div class="dre-line"><span>Despesas à vista</span><strong class="negative">${formatBRL(d.cashExpense)}</strong></div><div class="dre-line"><span>Compras no cartão</span><strong class="negative">${formatBRL(d.cardExpense)}</strong></div><div class="dre-line"><span>Despesas totais</span><strong>${formatBRL(d.totalExpense)}</strong></div><div class="dre-line total"><span>Resultado</span><strong class="${d.result>=0?'positive':'negative'}">${formatBRL(d.result)}</strong></div></div>`;openDialog('dre-dialog')}
function downloadPDF(refDate=dashboardDate){const d=getDRE(refDate);if(!window.jspdf?.jsPDF)return toast('Biblioteca de PDF ainda está carregando.','error');const doc=new window.jspdf.jsPDF();doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text('Family Finance',18,20);doc.setFontSize(13);doc.text(`Relatório mensal — ${monthLabel(refDate)}`,18,30);doc.setFont('helvetica','normal');doc.setFontSize(11);let y=45;[['Receitas',d.income],['Despesas à vista',d.cashExpense],['Compras no cartão',d.cardExpense],['Despesas totais',d.totalExpense],['Resultado',d.result]].forEach(([label,value])=>{doc.text(label,18,y);doc.text(formatBRL(value),140,y);y+=9});doc.text('Lançamentos',18,y+8);y+=17;state.transactions.filter(t=>String(t.occurred_on).startsWith(monthPrefix(refDate))).slice(0,35).forEach(t=>{doc.setFontSize(9);doc.text(`${formatDate(t.occurred_on)}  ${String(t.description).slice(0,45)}`,18,y);doc.text(`${Number(t.direction)>0?'+':'-'} ${formatBRL(t.amount)}`,140,y);y+=7;if(y>280){doc.addPage();y=20}});doc.save(`family-finance-${monthPrefix(refDate)}.pdf`)}

async function onTransactionSubmit(event){event.preventDefault();const btn=document.getElementById('transaction-save-btn');setButtonBusy(btn,true);setFormError('transaction-form-error','');try{const id=document.getElementById('transaction-id').value;const input={direction:Number(document.getElementById('transaction-direction').value),description:document.getElementById('transaction-description').value,amount:Number(document.getElementById('transaction-amount').value),date:document.getElementById('transaction-date').value,category:document.getElementById('transaction-category').value,notes:document.getElementById('transaction-notes').value,recurring:document.getElementById('transaction-recurring').checked,recurringCount:Number(document.getElementById('transaction-recurring-count').value)};if(!input.description.trim()||!input.date||input.amount<=0)throw new Error('Preencha descrição, data e um valor maior que zero.');if(id)await updateTransaction(id,input);else await createTransaction(input);closeDialog('transaction-dialog');toast(id?'Lançamento atualizado.':'Lançamento salvo.','success');await refreshAll()}catch(e){console.error(e);setFormError('transaction-form-error',e.message||'Não foi possível salvar.')}finally{setButtonBusy(btn,false)}}
async function onBalanceSubmit(event){event.preventDefault();const btn=document.getElementById('balance-save-btn');setButtonBusy(btn,true);setFormError('balance-form-error','');try{const input={mode:document.getElementById('balance-mode').value,amount:Number(document.getElementById('balance-amount').value),reason:document.getElementById('balance-reason').value,date:document.getElementById('balance-date').value};if(input.amount<0||!input.reason.trim()||!input.date)throw new Error('Informe valor, motivo e data.');await applyBalanceAdjustment(input);closeDialog('balance-dialog');toast('Saldo ajustado.','success');await refreshAll()}catch(e){console.error(e);setFormError('balance-form-error',e.message||'Não foi possível ajustar o saldo.')}finally{setButtonBusy(btn,false)}}
async function onCardSubmit(event){event.preventDefault();const btn=document.getElementById('card-save-btn');setButtonBusy(btn,true);setFormError('card-form-error','');try{const id=document.getElementById('card-id').value;const input={name:document.getElementById('card-name').value,limit:Number(document.getElementById('card-limit').value),closingDay:Number(document.getElementById('card-closing').value),dueDay:Number(document.getElementById('card-due').value),interest:Number(document.getElementById('card-interest').value||0)};if(!input.name.trim()||input.limit<0||input.closingDay<1||input.closingDay>31||input.dueDay<1||input.dueDay>31)throw new Error('Revise nome, limite, fechamento e vencimento.');if(id)await updateCard(id,input);else await createCard(input);closeDialog('card-dialog');toast(id?'Cartão atualizado.':'Cartão criado.','success');await refreshAll()}catch(e){console.error(e);setFormError('card-form-error',e.message||'Não foi possível salvar o cartão.')}finally{setButtonBusy(btn,false)}}
async function onPurchaseSubmit(event){event.preventDefault();const btn=document.getElementById('purchase-save-btn');setButtonBusy(btn,true);setFormError('purchase-form-error','');try{const id=document.getElementById('purchase-id').value;const input={cardId:document.getElementById('purchase-card-id').value,description:document.getElementById('purchase-description').value,total:Number(document.getElementById('purchase-total').value),installments:Number(document.getElementById('purchase-installments').value),date:document.getElementById('purchase-date').value,category:document.getElementById('purchase-category').value};if(!input.description.trim()||input.total<=0||!input.date||input.installments<1||input.installments>60)throw new Error('Revise descrição, valor, data e parcelas.');if(id)await updatePurchase(id,input);else await createPurchase(input);closeDialog('purchase-dialog');toast(id?'Compra atualizada.':'Compra salva e parcelas geradas.','success');await refreshAll()}catch(e){console.error(e);setFormError('purchase-form-error',e.message||'Não foi possível salvar a compra.')}finally{setButtonBusy(btn,false)}}
async function onGoalSubmit(event){event.preventDefault();const btn=document.getElementById('goal-save-btn');setButtonBusy(btn,true);setFormError('goal-form-error','');try{const id=document.getElementById('goal-id').value;const input={name:document.getElementById('goal-name').value,target:Number(document.getElementById('goal-target').value),saved:Number(document.getElementById('goal-saved').value||0),dueDate:document.getElementById('goal-due').value};if(!input.name.trim()||input.target<=0||input.saved<0)throw new Error('Revise nome e valores da meta.');if(id)await updateGoal(id,input);else await createGoal(input);closeDialog('goal-dialog');toast(id?'Meta atualizada.':'Meta criada.','success');await refreshAll()}catch(e){console.error(e);setFormError('goal-form-error',e.message||'Não foi possível salvar a meta.')}finally{setButtonBusy(btn,false)}}
async function onBudgetSave(){const btn=document.getElementById('save-budget-btn');setButtonBusy(btn,true);try{const limits={};document.querySelectorAll('[data-budget-category]').forEach(input=>limits[input.dataset.budgetCategory]=Number(input.value||0));state.budget=await saveBudget(budgetDate,Number(document.getElementById('budget-income').value||0),limits);toast('Orçamento salvo.','success');renderBudget();renderHome()}catch(e){console.error(e);toast(e.message||'Não foi possível salvar o orçamento.','error')}finally{setButtonBusy(btn,false)}}


async function onFamilyInviteSubmit(event){event.preventDefault();const btn=document.getElementById('family-invite-save');setButtonBusy(btn,true,'Enviando…');setFormError('family-invite-error','');try{await sendFamilyInvite(document.getElementById('family-invite-email').value);closeDialog('family-invite-dialog');toast('Convite enviado.','success');await refreshAll()}catch(e){console.error(e);setFormError('family-invite-error',e.message||'Não foi possível enviar o convite.')}finally{setButtonBusy(btn,false)}}
async function onFamilyPermissionsSubmit(event){event.preventDefault();const btn=document.getElementById('family-permissions-save');setButtonBusy(btn,true);setFormError('family-permissions-error','');try{await updateFamilyPermissions(document.getElementById('family-link-id').value,{transactions:document.getElementById('perm-transactions').checked,cards:document.getElementById('perm-cards').checked,goals:document.getElementById('perm-goals').checked,budget:document.getElementById('perm-budget').checked});closeDialog('family-permissions-dialog');toast('Permissões atualizadas.','success');await refreshAll()}catch(e){console.error(e);setFormError('family-permissions-error',e.message||'Não foi possível salvar as permissões.')}finally{setButtonBusy(btn,false)}}
async function onProfileSettingsSubmit(event){event.preventDefault();const btn=document.getElementById('save-profile-settings-btn');setButtonBusy(btn,true);try{currentProfile=await updateProfileSettings({displayName:document.getElementById('settings-display-name').value});showApp(currentUser,currentProfile);toast('Nome atualizado.','success');renderSettings()}catch(e){console.error(e);toast('Não foi possível atualizar o perfil.','error')}finally{setButtonBusy(btn,false)}}
async function onLegacyMigrationSubmit(event){event.preventDefault();const btn=document.getElementById('legacy-migration-btn');setButtonBusy(btn,true,'Migrando…');setFormError('migration-error','');try{const result=await claimLegacyAccount(document.getElementById('legacy-username').value,document.getElementById('legacy-password').value);document.getElementById('legacy-password').value='';currentProfile=await ensureProfile(currentUser);showApp(currentUser,currentProfile);toast(`Migração concluída: ${result.transactions||0} lançamentos e ${result.goals||0} metas importados.`,'success');await refreshAll()}catch(e){console.error(e);setFormError('migration-error',e.message||'Não foi possível migrar os dados.')}finally{setButtonBusy(btn,false)}}

async function handleDynamicClick(event){const target=event.target.closest('button');if(!target)return;try{
  if(target.dataset.familyRespond){await respondFamilyInvite(target.dataset.familyRespond,target.dataset.accept==='1');toast(target.dataset.accept==='1'?'Convite aceito.':'Convite recusado.','success');return refreshAll()}
  if(target.dataset.familyCancelInvite){await cancelFamilyInvite(target.dataset.familyCancelInvite);toast('Convite cancelado.','success');return refreshAll()}
  if(target.dataset.familyPermissions)return openFamilyPermissions(target.dataset.familyPermissions);
  if(target.dataset.familyMonitor)return openFamilyMonitor(target.dataset.familyMonitor);
  if(target.dataset.familyRemove){if(!confirm('Remover este vínculo familiar?'))return;await removeFamilyLink(target.dataset.familyRemove);toast('Vínculo removido.','success');document.getElementById('family-monitor-panel').classList.add('hidden');return refreshAll()}

  if(target.dataset.editTransaction)return openEditTransaction(target.dataset.editTransaction);
  if(target.dataset.deleteTransaction){const id=target.dataset.deleteTransaction;const t=state.transactions.find(x=>x.id===id);const series=!!t?.recurring_group_id;let removeSeries=false;if(series){removeSeries=confirm('Este lançamento é recorrente. OK = excluir toda a série. Cancelar = escolher apenas esta ocorrência.');if(!removeSeries&&!confirm('Excluir somente esta ocorrência?'))return;}else if(!confirm('Excluir este lançamento?'))return;await deleteTransaction(id,removeSeries);toast('Lançamento excluído.','success');return refreshAll()}
  if(target.dataset.editCard)return openEditCard(target.dataset.editCard);
  if(target.dataset.deleteCard){if(!confirm('Excluir o cartão e todas as compras/parcelas vinculadas?'))return;await deleteCard(target.dataset.deleteCard);toast('Cartão excluído.','success');return refreshAll()}
  if(target.dataset.newPurchase)return openNewPurchase(target.dataset.newPurchase);
  if(target.dataset.editPurchase)return openEditPurchase(target.dataset.editPurchase);
  if(target.dataset.deletePurchase){if(!confirm('Excluir esta compra e suas parcelas?'))return;await deletePurchase(target.dataset.deletePurchase);toast('Compra excluída.','success');return refreshAll()}
  if(target.dataset.openInvoice)return openInvoice(target.dataset.openInvoice);
  if(target.dataset.toggleInvoice){const cardId=target.dataset.toggleInvoice;const paid=target.dataset.invoicePaid==='1';await setInvoicePaid(cardId,`${dashboardDate.getFullYear()}-${String(dashboardDate.getMonth()+1).padStart(2,'0')}-01`,!paid);toast(!paid?'Fatura marcada como paga.':'Fatura reaberta.','success');closeDialog('invoice-dialog');await refreshAll();return openInvoice(cardId)}
  if(target.dataset.editGoal)return openEditGoal(target.dataset.editGoal);
  if(target.dataset.deleteGoal){if(!confirm('Excluir esta meta?'))return;await deleteGoal(target.dataset.deleteGoal);toast('Meta excluída.','success');return refreshAll()}
  if(target.dataset.goModule)return showModule(target.dataset.goModule);
}catch(e){console.error(e);toast(e.message||'Não foi possível concluir a ação.','error')}}

function bindUI(){setAuthMode(authMode);fillCategorySelect('transaction-category');fillCategorySelect('purchase-category');document.getElementById('transaction-filter-month').value=monthInputValue(dashboardDate);
  document.getElementById('auth-toggle').addEventListener('click',()=>{authMode=authMode==='login'?'register':'login';setAuthError('');setAuthMode(authMode)});
  document.getElementById('auth-form').addEventListener('submit',async event=>{event.preventDefault();setAuthError('');const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,displayName=document.getElementById('display-name').value.trim();if(!email||!password)return setAuthError('Informe e-mail e senha.');if(password.length<6)return setAuthError('A senha precisa ter pelo menos 6 caracteres.');if(authMode==='register'&&!displayName)return setAuthError('Informe seu nome.');setAuthBusy(true,authMode);try{if(authMode==='register'){const {data,error}=await signUp(email,password,displayName);if(error)throw error;if(data.session)await enterApp(data.session);else toast('Conta criada. Verifique seu e-mail para confirmar o acesso.','success')}else{const {data,error}=await signIn(email,password);if(error)throw error;await enterApp(data.session)}}catch(error){console.error(error);setAuthError(error?.message?.includes('Invalid login credentials')?'E-mail ou senha inválidos.':(error?.message||'Não foi possível autenticar.'))}finally{setAuthBusy(false,authMode)}});
  document.querySelectorAll('.nav-item[data-module]').forEach(b=>b.addEventListener('click',()=>showModule(b.dataset.module)));document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.closeDialog)));document.querySelectorAll('[data-go-module]').forEach(b=>b.addEventListener('click',()=>showModule(b.dataset.goModule)));document.querySelectorAll('.mobile-nav-item[data-module]').forEach(b=>b.addEventListener('click',()=>showModule(b.dataset.module)));document.getElementById('mobile-more-btn').addEventListener('click',()=>openDialog('mobile-more-dialog'));document.querySelectorAll('[data-mobile-go]').forEach(b=>b.addEventListener('click',()=>{closeDialog('mobile-more-dialog');showModule(b.dataset.mobileGo)}));
  document.getElementById('logout-btn').addEventListener('click',async()=>{const {error}=await signOut();if(error)return toast('Não foi possível encerrar a sessão.','error');showAuth()});document.getElementById('mobile-logout-btn').addEventListener('click',async()=>{closeDialog('mobile-more-dialog');const {error}=await signOut();if(error)return toast('Não foi possível encerrar a sessão.','error');showAuth()});
  document.getElementById('new-transaction-btn').addEventListener('click',openNewTransaction);document.getElementById('quick-transaction').addEventListener('click',openNewTransaction);document.getElementById('open-balance-adjust').addEventListener('click',openBalance);document.getElementById('new-card-btn').addEventListener('click',openNewCard);document.getElementById('new-goal-btn').addEventListener('click',openNewGoal);document.getElementById('quick-dre').addEventListener('click',openDRE);document.getElementById('budget-dre-btn').addEventListener('click',()=>openDRE(budgetDate));document.getElementById('quick-pdf').addEventListener('click',downloadPDF);document.getElementById('budget-pdf-btn').addEventListener('click',()=>downloadPDF(budgetDate));document.getElementById('save-budget-btn').addEventListener('click',onBudgetSave);
  document.getElementById('transaction-form').addEventListener('submit',onTransactionSubmit);document.getElementById('balance-form').addEventListener('submit',onBalanceSubmit);document.getElementById('card-form').addEventListener('submit',onCardSubmit);document.getElementById('purchase-form').addEventListener('submit',onPurchaseSubmit);document.getElementById('goal-form').addEventListener('submit',onGoalSubmit);document.getElementById('family-invite-form').addEventListener('submit',onFamilyInviteSubmit);document.getElementById('family-permissions-form').addEventListener('submit',onFamilyPermissionsSubmit);document.getElementById('profile-settings-form').addEventListener('submit',onProfileSettingsSubmit);document.getElementById('legacy-migration-form').addEventListener('submit',onLegacyMigrationSubmit);document.getElementById('new-family-invite-btn').addEventListener('click',()=>{document.getElementById('family-invite-form').reset();setFormError('family-invite-error','');openDialog('family-invite-dialog')});document.getElementById('family-monitor-close').addEventListener('click',()=>document.getElementById('family-monitor-panel').classList.add('hidden'));document.querySelectorAll('[data-theme-choice]').forEach(btn=>btn.addEventListener('click',async()=>{try{currentProfile=await updateProfileSettings({theme:btn.dataset.themeChoice});applyTheme(currentProfile.theme);toast('Tema atualizado.','success')}catch(e){console.error(e);toast('Não foi possível salvar o tema.','error')}}));
  document.getElementById('transaction-recurring').addEventListener('change',e=>document.getElementById('recurring-count-wrap').classList.toggle('hidden',!e.target.checked));['transaction-search','transaction-filter-type','transaction-filter-month'].forEach(id=>document.getElementById(id).addEventListener(id==='transaction-search'?'input':'change',renderTransactions));
  document.querySelectorAll('[data-month-action]').forEach(b=>b.addEventListener('click',async()=>{dashboardDate=addMonth(dashboardDate,b.dataset.monthAction==='next'?1:-1);budgetDate=new Date(dashboardDate);document.getElementById('transaction-filter-month').value=monthInputValue(dashboardDate);setLoading(true);try{state.budget=await getBudget(budgetDate);renderHome();renderBudget()}catch(e){toast('Não foi possível carregar o mês.','error')}finally{setLoading(false)}}));document.querySelectorAll('[data-budget-month]').forEach(b=>b.addEventListener('click',async()=>{budgetDate=addMonth(budgetDate,b.dataset.budgetMonth==='next'?1:-1);setLoading(true);try{state.budget=await getBudget(budgetDate);renderBudget()}catch(e){toast('Não foi possível carregar o orçamento.','error')}finally{setLoading(false)}}));document.addEventListener('click',handleDynamicClick)}

async function init(){bindUI();await initPWA();const session=await getSession().catch(()=>null);if(session)await enterApp(session);else showAuth();onAuthChange(async next=>{if(next)await enterApp(next);else showAuth()})}
init();
